### ISSUE TITLE
Background color in the blended plot

### ISSUE THREAD

**Issue by ElyasMo** [george-hall-ucl/SpatialFeaturePlotBlend#1]
Thanks for this useful implementation.

I was wondering if one can change the background color. Now it is black by default. I see that in the first two plots, it is easy to change the colors:

```r
function(feature) {
                                max_color <- ifelse(feature == features[1],
                                                    "#FF0000", "#00FF00")   
                                SpatialFeaturePlot(object, feature,
                                                   images = i, ...) +
                                    scale_fill_gradient(low = "#000000",
                                                        high = max_color) +
                                    ggtitle(feature) +
                                    blend_plot_theme
                            })

```

But the problem arise in the third plot which is the blended plot of the first two and also the color scheme square in the right. I believe the codes for the colors of this part is:

```r
as_hex <- function(num) {
        hex_str <- as.character(as.hexmode(num))
        if (nchar(hex_str) == 1) {
            hex_str <- paste0("0", hex_str)
        }

        return(hex_str)
    }

    metadata_to_hexadecimal <- function(in_dat) {
        apply(in_dat, 2,
              function(x) {
                  # Make minimum 0
                  x - min(x)
              }) %>%
        apply(2,
              function(x) {
                  # Constrain to range [0, 255]
                  round(255 * (x / max(x)))
              }) %>%
        apply(1,
              function(x) {
                  # Convert to hexadecimal codes
                  toupper(paste0("#", as_hex(x[1]), as_hex(x[2]), "00"))
              })
    }
    
```

I tried and I could not revise the codes in a way to make the background white which make the plot consistent with for instance this code :

```r
function(feature) {
                                max_color <- ifelse(feature == features[1],
                                                    "gold2", "purple2")
                                SpatialFeaturePlot(object, feature,
                                                   images = i, ...) +
                                    scale_fill_gradient(low = "white",
                                                        high = max_color) +
                                    ggtitle(feature) +
                                    blend_plot_theme
                            })

```

This as you can see makes the first two plots in "gold2", "purple2" respectively with a white background but I could not find anyway to make the third and fourth plots consistent with the first two.

This would be extremely helpful as minor changes are more visible in a white background.

**Comment by george-hall-ucl** [comment]
Hi @ElyasMo,

Thank you for your interest and for your code! I actually fixed this issue locally a little while ago but it looks like I forgot to push my fix to this repo - sorry! I've now pushed this change. I think it provides the solution you want, but let me know if not. You can see the new functionality [here](https://github.com/george-hall-ucl/SpatialFeaturePlotBlend?tab=readme-ov-file#custom-colors).

Thanks,
George
